# Generated by Django 6.0.7 on 2026-07-22 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Live demo or website link (optional)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository link (optional)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(default='', help_text='Short summary shown on the main homepage card', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(default='', help_text='Cover picture or GIF for the home page card', upload_to='projects/thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Full detailed description shown on the project page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(help_text='e.g. Django, PHP Laravel, React, Python', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/gallery/')),
                ('media_type', models.CharField(choices=[('image', 'Image or GIF'), ('video', 'Video (MP4)')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='portfolio.project')),
            ],
        ),
    ]
